name: Java CI with Maven

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.2 # Fixed Node 24 compatibility in later v4 patches

      - name: Set up JDK 25
        uses: actions/setup-java@v5   # Upgraded to v5 to officially support Node 24
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run Tests
        run: mvn clean test
