name: Java CI with Maven

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin' # Installs the Eclipse Temurin build of JDK 25
          cache: maven            # Speeds up your workflow by caching dependencies

      - name: Build and Run Tests
        run: mvn clean test
